export const SELECT_REGION = 'SELECT_REGION';
export const CLEAR_SELECTED_REGION = 'CLEAR_SELECTED_REGION';
export const SET_MAP_DATA = 'SET_MAP_DATA';
export const FETCH_MAP_DATA_FAILED = 'FETCH_MAP_DATA_FAILED';
export const FETCH_MAP_DATA_START = 'FETCH_MAP_DATA_START';