export const SELECT_REGION = 'SELECT_REGION';
export const CLEAR_SELECTED_REGION = 'CLEAR_SELECTED_REGION';
export const SET_MAP_DATA = 'SET_MAP_DATA';
export const FETCH_MAP_DATA_FAILED = 'FETCH_MAP_DATA_FAILED';
export const FETCH_MAP_DATA_START = 'FETCH_MAP_DATA_START';
export const MAP_HOVER = 'MAP_HOVER';
export const MAP_HOVER_LEAVE = 'MAP_HOVER_LEAVE';